### ISSUE TITLE
backspace (in insert mode) frozen after having sent lines to interactive program

### ISSUE THREAD

**Issue by fruzsinaagocs** [williamjameshandley/vimteractive#1]
### Description of issue: 

In insert mode, pressing backspace doesn't delete *some* characters.

### When does it occur? 

It happens after one has sent a line (`ctrl+s`) to the interactive program of choice, then tries to edit the same line in insert mode. The following characters  cannot be deleted with backspace:
1. those written prior to sending the line and entering insert mode (since the last `ctrl+s`). This makes it impossible to edit a line and re-send it to the interactive program.
2. those written between having sent the line to the interactive program, and exiting then re-entering insert mode (`esc` + `i`). This makes it impossible to write new lines "in several turns", i.e. whilst switching between command and insert modes.

_However:_
- sometimes appending to these characters first in insert mode then lets you delete them,
- one can still edit any line in command mode .

### To reproduce the issue:

1.  Write any line.
2. Enter command mode and open maple: `:Imaple`.
3. Send line to maple: `ctrl+S`.
4. Enter insert mode and try deleting some characters in the line (issue 1 above)
5. Write a new line below the previous one.
6. Exit insert mode and re-enter it: `esc` and `i`.
7. Try deleting some characters in the second line (issue 2 above).

**Comment by williamjameshandley** [comment]
I believe the update for version 1.1 fixed this issue. Are you still experiencing it?
