### ISSUE TITLE
Send selected text to Ipython console

### ISSUE THREAD

**Issue by DKioroglou** [williamjameshandley/vimteractive#14]
This is a great implentation. Thank you for creating this plugin.    

Would it be possible to send selected text to the console?   
I have tried it but still it sends the whole line where the selected text is. 

This feature would be great in situations where one wants to evaluate a small snippet of code without having to switch to the console.

**Comment by williamjameshandley** [comment]
Hi @DKioroglou . Many thanks for your feedback. I agree that this would be a much more intuitive way of interpreting control-S with visual selection, and can think of instances in the past when I could have used this functionality.

Does #15 provide the functionality you require? Are you able to test that code on your system to confirm that it works as you expect?
