### ISSUE TITLE
neovim compatible?

### ISSUE THREAD

**Issue by spring-haru** [williamjameshandley/vimteractive#16]
I installed `vimteractive` in neovim v0.4.2, and a command `:terminal` works fine. But when I run `:Iipython`, the following error is generated:

`Your version of vim is not compiled with +terminal. Cannot use vimteractive
`

Is `vimteractive` compatible with neovim?

GitHub page says 

`vimteractive is only compatible with vim 8 or greater`

Does it exclude neovim?

**Comment by williamjameshandley** [comment]
Hi @spring-haru . I don't use neovim, so I don't know if anybody has tried this yet. If you comment out / delete the lines 101-104 in `autoload/vimteractive.vim`, do you find that it works? It may just be that it needs a different check for neovim.

**Comment by spring-haru** [comment]
After commenting out the lines 101-104 in `autoload/vimteractive.vim` and restarting neovim, `:Iipython` generates no error, saying `Starting python --matplotlib --no-autoindent`. But, that is all. No iPython preview window is opened.  Then, with the cursor in the `.py` file, pressing CTRL-S opens a horizontally split window with the same `.py` file, generating the following error message:
```
Error detected while processing function vimteractive#sendlines[19]..<SNR>114_show_term:
line    4:
E94: No matching buffer for -1
Error detected while processing function vimteractive#sendlines:
line   25:
E117: Unknown function: term_sendkeys
```

**Comment by v-i-s-h** [comment]
same problem here

**Comment by williamjameshandley** [comment]
I'm afraid that at the moment vimteractive is not able to support neovim. I would be more than happy to consider a pull request from someone with experience adapting vim scripts to be neovim compatible.
