### ISSUE TITLE
Vertical split

### ISSUE THREAD

**Issue by AlexisRenchon** [williamjameshandley/vimteractive#19]
Hi, 
I am new to VIM so this may be an obvious one. 
I prefer vertical split to horizontal split, but the default :Ijulia (I use Julia) open the terminal in a horizontal split.

I tried :vert Ijulia, but it also opens Julia in a horizontal split.  

Thanks!

EDIT: :vertical ball works.

**Comment by williamjameshandley** [comment]
Hi @AlexisRenchon. I agree that this would be great functionality to have, and that the most vim-like way of doing it would be with a `:vertical` command modifier. 

I've spent some time looking into this, and unless I'm mistaken it's not possible to access command modifiers through vimscript, only the full C API, so the implementation that you suggest with the `:vertical` command modifier I don't think is going to be possible.

There is a reasonable half-way solution you can use now, which is to run `:Ijulia` as before, and then key `<ctrl>-w H`, or `<ctrl>-W L` which should move the split as you require (note the capital H). 

A more long-term solution would be to have a vimteractive parameter `g:vimteractive_vertical` that you can set in your `.vimrc`, which would then toggle what the default splitting behaviour is. Would this suffice? I've put in a potential PR #21. If you clone down the `vertical_option` branch and install from that, could you test that out and see if that works for you?

**Comment by AlexisRenchon** [comment]
Hi @williamjameshandley , thank you so much for the fast reply and branch!
I copied #21 , and added - let g:vimteractive_vertical = 1  " Vertically split terminals -  to my .vimrc file. It works well. 
Note that it puts the terminal (julia for me) on the left, and I prefer to have it on the right. But using <C-w> <C-r> swap the two windows, so this is fine.

**Comment by williamjameshandley** [comment]
Many thanks @AlexisRenchon  I've now merged that into master.

>EDIT: also, the option of having ctrl-S going to the next line would be nice too!

I think this would be a breaking change, but an alternative keyboard shortcut could provide this functionality. If you're able to have a go at implementing and testing this yourself, then feel free to [submit it as a PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork). You should raise this as a separate issue regardless.
