### ISSUE TITLE
Buffer name choice causing error.

### ISSUE THREAD

**Issue by saltycraig** [williamjameshandley/vimteractive#2]
Naming the buffer used for the repl "Vimteractive" causes false positive when you have the documentation open (also called "Vimteractive") in another buffer.

**Comment by williamjameshandley** [comment]
Hi @saltycraig 

Does PR #3 fix your issue?

Many thanks for your feedback. Please let me know if you have any other requests for functionality/bugs.  At the moment the source is still pretty readable in `plugin/vimteractive.vim`, so alternatively you may be able to modify it to suit your needs and then submit it as a pull request

**Comment by saltycraig** [comment]
Yes, that does it. I figured that would be easiest fix, but didn't want to impose the PR on you with my choice for a buffer name. I have a few ideas I'll put together, separated into PRs, thanks!
