### ISSUE TITLE
No new line on windows

### ISSUE THREAD

**Issue by blayz3r** [williamjameshandley/vimteractive#22]
I tried to replicate the example in the **_read me_** on Windows 10 and it looks like the new line character is not recognized:

![image](https://user-images.githubusercontent.com/12205650/70855344-5b5df280-1e97-11ea-9062-440d3c384525.png)

**Comment by williamjameshandley** [comment]
Hi there @blayz3r . Can you check to see whether PR #23 fixes this issue?

**Comment by blayz3r** [comment]
Yes, that works

**Comment by williamjameshandley** [comment]
Closed by #23
