### ISSUE TITLE
Can't use ctrl-s in visual mode

### ISSUE THREAD

**Issue by AlexisRenchon** [williamjameshandley/vimteractive#26]
Hi Will, 
I am having some troubles running ctrl-s in visual mode. 
The command ctrl-s works as intended in normal mode and insert mode, but in visual mode it sends what I have in my clipboard to the terminal. 

Do you have an idea why? It does the same regardless of the terminal I open (:Ijulia, :Ipython, ...)

Thanks!

**Comment by AlexisRenchon** [comment]
I resinstalled VIM and it fixed it.

**Comment by williamjameshandley** [comment]
Hi @AlexisRenchon . Many thanks for resolving this. I imagine that this issue was resolved by #23, and reinstalling vim fixed your issue because you ended up updating vimteractive.
