### ISSUE TITLE
Prevent automatic scroll on switching splits

### ISSUE THREAD

**Issue by physicophilic** [williamjameshandley/vimteractive#31]
Switching between vim splits causes vimteractive session to scroll to the bottom - which doesn't happen in usual vim terminal. 

While reading stack traces for errors with REPL opened in vimteractive, this causes a big problem. I took a quick look through the plugin files but can't see the reason for this. How to fix it (at least temporarily?)
     
By the way, a great plugin. It's very simple.

**Comment by williamjameshandley** [comment]
Hi @physicophilic. This is something that has been irritating me for a while too. I think I've found a fix for this on #32. If you're able to, could you confirm that this branch gives you the behaviour you want? Easiest is to uninstall the current version, and then copy the two files

https://raw.githubusercontent.com/williamjameshandley/vimteractive/prevent_automatic_scroll/autoload/vimteractive.vim
https://raw.githubusercontent.com/williamjameshandley/vimteractive/prevent_automatic_scroll/ftplugin/vimteractive.vim

into `~/.vim/autoload/vimteractive.vim` and `~/.vim/ftplugin/vimteractive.vim`

**Comment by physicophilic** [comment]
The second link isn't working. Replacing only the first file fixed the automatic scrolling though. I am not sure if that's the right way to do it.

**Comment by williamjameshandley** [comment]
Apologies. I've corrected the link now (should have been plugin, rather than ftplugin), but as that file isn't changed this shows the fix works. I'll merge and update accordingly.
