### ISSUE TITLE
feature request: wolfram support

### ISSUE THREAD

**Issue by fruzsinaagocs** [williamjameshandley/vimteractive#33]
Mathematica also has a command-line interface (accessible by typing `wolfram` in the terminal) and can accept scripts (`<filename>.wls` files). Will there be support for this in the future?

**Comment by williamjameshandley** [comment]
I did not know this, and should definitely be added! Feel free to submit a PR with the relevant modifications to `plugin/vimteractive.vim`

For local testing, I tend to uninstall vimteractive via whatever mechanism you usually include, and then clone the github repo before symlinking `plugin/vimteractive.vim` and `autoload/vimteractive.vim` into `~/.vim/plugin/vimeractive.vim` and `~/.vim/autoload/vimteractive.vim` (or whatever your OS equivalent is).

**Comment by williamjameshandley** [comment]
@fruzsinaagocs have you tried this out on your local system?

**Comment by williamjameshandley** [comment]
I implemented this a while back:
7a24aefd0372460391e58136a4e1ec174583d89a
